//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityContext : DbContext
    {
        public EntityContext()
            : base("name=EntityContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bx_crm_steps> bx_crm_steps { get; set; }
        public DbSet<manageruser> manageruser { get; set; }
        public DbSet<manager_role_module_relation> manager_role_module_relation { get; set; }
        public DbSet<manager_role_db> manager_role_db { get; set; }
        public DbSet<manager_module_db> manager_module_db { get; set; }
        public DbSet<bx_transferrecord> bx_transferrecord { get; set; }
        public DbSet<bx_tagsetting> bx_tagsetting { get; set; }
        public DbSet<bx_tagsetting_agent_relationship> bx_tagsetting_agent_relationship { get; set; }
        public DbSet<bx_submit_info> bx_submit_info { get; set; }
        public DbSet<bx_sms_account> bx_sms_account { get; set; }
        public DbSet<bx_sms_account_content> bx_sms_account_content { get; set; }
        public DbSet<bx_savequote> bx_savequote { get; set; }
        public DbSet<bx_renewalquote> bx_renewalquote { get; set; }
        public DbSet<bx_reconciliation> bx_reconciliation { get; set; }
        public DbSet<bx_lastinfo> bx_lastinfo { get; set; }
        public DbSet<bx_hebaodianwei> bx_hebaodianwei { get; set; }
        public DbSet<bx_gsc_userinfo> bx_gsc_userinfo { get; set; }
        public DbSet<bx_claim_detail> bx_claim_detail { get; set; }
        public DbSet<bx_city> bx_city { get; set; }
        public DbSet<bx_charge> bx_charge { get; set; }
        public DbSet<bx_charge_history> bx_charge_history { get; set; }
        public DbSet<bx_carinfo> bx_carinfo { get; set; }
        public DbSet<bx_car_order> bx_car_order { get; set; }
        public DbSet<bx_agent_ukey> bx_agent_ukey { get; set; }
        public DbSet<bx_agent_token> bx_agent_token { get; set; }
        public DbSet<bx_agent_special_rate> bx_agent_special_rate { get; set; }
        public DbSet<bx_agent_report> bx_agent_report { get; set; }
        public DbSet<bx_agent_rate> bx_agent_rate { get; set; }
        public DbSet<bx_agent_distributed> bx_agent_distributed { get; set; }
        public DbSet<bx_quoteresult_carinfo> bx_quoteresult_carinfo { get; set; }
        public DbSet<bx_userinfo_renewal_info> bx_userinfo_renewal_info { get; set; }
        public DbSet<bx_agent_config> bx_agent_config { get; set; }
        public DbSet<bx_cityquoteday> bx_cityquoteday { get; set; }
        public DbSet<bx_carmodel> bx_carmodel { get; set; }
        public DbSet<bx_tempinsuredinfo> bx_tempinsuredinfo { get; set; }
        public DbSet<bx_quoterenewal_agent_config> bx_quoterenewal_agent_config { get; set; }
        public DbSet<bx_quoterenewal_city_config> bx_quoterenewal_city_config { get; set; }
        public DbSet<bx_system_message> bx_system_message { get; set; }
        public DbSet<bx_notice_xb> bx_notice_xb { get; set; }
        public DbSet<bx_temprelation_intermediate_userinfo> bx_temprelation_intermediate_userinfo { get; set; }
        public DbSet<bx_sms_order> bx_sms_order { get; set; }
        public DbSet<bx_agentpoint> bx_agentpoint { get; set; }
        public DbSet<bx_appsetting> bx_appsetting { get; set; }
        public DbSet<bx_area> bx_area { get; set; }
        public DbSet<bx_buid_activity> bx_buid_activity { get; set; }
        public DbSet<bx_bj_union> bx_bj_union { get; set; }
        public DbSet<bx_order_quoteresult> bx_order_quoteresult { get; set; }
        public DbSet<bx_order_savequote> bx_order_savequote { get; set; }
        public DbSet<bx_order_submit_info> bx_order_submit_info { get; set; }
        public DbSet<bx_order_userinfo> bx_order_userinfo { get; set; }
        public DbSet<bx_devicedetail> bx_devicedetail { get; set; }
        public DbSet<bx_gsc_renewal> bx_gsc_renewal { get; set; }
        public DbSet<bx_history_contract> bx_history_contract { get; set; }
        public DbSet<bx_images> bx_images { get; set; }
        public DbSet<bx_para_bhtype> bx_para_bhtype { get; set; }
        public DbSet<bx_report_claim> bx_report_claim { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<bj_baodanxianzhong> bj_baodanxianzhong { get; set; }
        public DbSet<bx_camera_config> bx_camera_config { get; set; }
        public DbSet<bx_forbid_mobile> bx_forbid_mobile { get; set; }
        public DbSet<bx_msgindex> bx_msgindex { get; set; }
        public DbSet<bx_defeatreasonhistory> bx_defeatreasonhistory { get; set; }
        public DbSet<bx_defeatreasonsetting> bx_defeatreasonsetting { get; set; }
        public DbSet<bx_forbid_record> bx_forbid_record { get; set; }
        public DbSet<bx_agent_xgaccount_relationship> bx_agent_xgaccount_relationship { get; set; }
        public DbSet<bx_config> bx_config { get; set; }
        public DbSet<manager_user_role_relation> manager_user_role_relation { get; set; }
        public DbSet<bx_agent_wchat> bx_agent_wchat { get; set; }
        public DbSet<bx_zuoxi> bx_zuoxi { get; set; }
        public DbSet<dd_order_quoteresult> dd_order_quoteresult { get; set; }
        public DbSet<dd_order_related_info> dd_order_related_info { get; set; }
        public DbSet<dd_order_savequote> dd_order_savequote { get; set; }
        public DbSet<bx_agent_busiuser> bx_agent_busiuser { get; set; }
        public DbSet<dd_order_paymentresult> dd_order_paymentresult { get; set; }
        public DbSet<bx_busiuser> bx_busiuser { get; set; }
        public DbSet<dd_order_steps> dd_order_steps { get; set; }
        public DbSet<bx_recycle_history> bx_recycle_history { get; set; }
        public DbSet<bx_customercategories> bx_customercategories { get; set; }
        public DbSet<bj_baodanxinxi> bj_baodanxinxi { get; set; }
        public DbSet<bx_companyrelation> bx_companyrelation { get; set; }
        public DbSet<bx_distributed_history> bx_distributed_history { get; set; }
        public DbSet<bx_message> bx_message { get; set; }
        public DbSet<bx_table_header> bx_table_header { get; set; }
        public DbSet<bx_tempuserinfo> bx_tempuserinfo { get; set; }
        public DbSet<bx_userinfo> bx_userinfo { get; set; }
        public DbSet<dd_pay_bank> dd_pay_bank { get; set; }
        public DbSet<dd_pay_way> dd_pay_way { get; set; }
        public DbSet<bx_login_log> bx_login_log { get; set; }
        public DbSet<bx_busiusersetting> bx_busiusersetting { get; set; }
        public DbSet<bx_customerstatus> bx_customerstatus { get; set; }
        public DbSet<bx_batchrenewal_erroritem> bx_batchrenewal_erroritem { get; set; }
        public DbSet<bx_batchrenewal_item> bx_batchrenewal_item { get; set; }
        public DbSet<bx_renewal_time_setting> bx_renewal_time_setting { get; set; }
        public DbSet<bx_batchrenewal_time_setting> bx_batchrenewal_time_setting { get; set; }
        public DbSet<dd_order_collection> dd_order_collection { get; set; }
        public DbSet<bx_consumer_review> bx_consumer_review { get; set; }
        public DbSet<manager_module_button> manager_module_button { get; set; }
        public DbSet<manager_role_button_relation> manager_role_button_relation { get; set; }
        public DbSet<bx_camera_history> bx_camera_history { get; set; }
        public DbSet<bx_ratepolicy_setting> bx_ratepolicy_setting { get; set; }
        public DbSet<bx_ratepolicy_item> bx_ratepolicy_item { get; set; }
        public DbSet<bx_camera_detail> bx_camera_detail { get; set; }
        public DbSet<bx_order> bx_order { get; set; }
        public DbSet<bx_bank> bx_bank { get; set; }
        public DbSet<bx_preferential_activity> bx_preferential_activity { get; set; }
        public DbSet<bx_agent_config_count> bx_agent_config_count { get; set; }
        public DbSet<bx_anxin_delivery> bx_anxin_delivery { get; set; }
        public DbSet<bx_epolicy> bx_epolicy { get; set; }
        public DbSet<bx_epolicy_log> bx_epolicy_log { get; set; }
        public DbSet<dd_pay_ax> dd_pay_ax { get; set; }
        public DbSet<bx_agent_withdrawal> bx_agent_withdrawal { get; set; }
        public DbSet<dd_order_commission> dd_order_commission { get; set; }
        public DbSet<bx_car_renewal> bx_car_renewal { get; set; }
        public DbSet<bx_userinfo_renewal_index> bx_userinfo_renewal_index { get; set; }
        public DbSet<bx_agent_bankcard> bx_agent_bankcard { get; set; }
        public DbSet<bx_zc_team_every_incoming_setting> bx_zc_team_every_incoming_setting { get; set; }
        public DbSet<bx_zc_team_incoming_setting> bx_zc_team_incoming_setting { get; set; }
        public DbSet<bx_zc_team_task_setting> bx_zc_team_task_setting { get; set; }
        public DbSet<bx_agent_answern_city> bx_agent_answern_city { get; set; }
        public DbSet<bx_camera_blacklist> bx_camera_blacklist { get; set; }
        public DbSet<bx_sms_order_error> bx_sms_order_error { get; set; }
        public DbSet<bx_agent_setting> bx_agent_setting { get; set; }
        public DbSet<bx_batchrenewal> bx_batchrenewal { get; set; }
        public DbSet<bx_sf_agent> bx_sf_agent { get; set; }
        public DbSet<bx_tagflag> bx_tagflag { get; set; }
        public DbSet<bx_quote_record> bx_quote_record { get; set; }
        public DbSet<bx_userinfo_expand> bx_userinfo_expand { get; set; }
        public DbSet<bx_batchrefreshrenewal> bx_batchrefreshrenewal { get; set; }
        public DbSet<bx_distributedtime> bx_distributedtime { get; set; }
        public DbSet<dz_baodanxianzhong> dz_baodanxianzhong { get; set; }
        public DbSet<bx_agent> bx_agent { get; set; }
        public DbSet<tx_cluedistributerulesetting> tx_cluedistributerulesetting { get; set; }
        public DbSet<tx_cluefollowuprecord> tx_cluefollowuprecord { get; set; }
        public DbSet<tx_clueinsureinfo> tx_clueinsureinfo { get; set; }
        public DbSet<tx_mobile_agent_relationship> tx_mobile_agent_relationship { get; set; }
        public DbSet<tx_noticemessage> tx_noticemessage { get; set; }
        public DbSet<tx_overnoticesetting> tx_overnoticesetting { get; set; }
        public DbSet<tx_receivesdistributerulesetting> tx_receivesdistributerulesetting { get; set; }
        public DbSet<tx_sms> tx_sms { get; set; }
        public DbSet<tx_smstemplatesetting> tx_smstemplatesetting { get; set; }
        public DbSet<tx_state> tx_state { get; set; }
        public DbSet<manager_function_db> manager_function_db { get; set; }
        public DbSet<manager_role_function_relation> manager_role_function_relation { get; set; }
        public DbSet<tx_clues_agent_relationship> tx_clues_agent_relationship { get; set; }
        public DbSet<tx_loss_reason> tx_loss_reason { get; set; }
        public DbSet<tx_operation_log> tx_operation_log { get; set; }
        public DbSet<tx_mobileservicestatus> tx_mobileservicestatus { get; set; }
        public DbSet<bx_quotereq_carinfo> bx_quotereq_carinfo { get; set; }
        public DbSet<tx_storeaddress> tx_storeaddress { get; set; }
        public DbSet<bx_address> bx_address { get; set; }
        public DbSet<bx_group_authen> bx_group_authen { get; set; }
        public DbSet<bx_quotehistory_related> bx_quotehistory_related { get; set; }
        public DbSet<tx_clues> tx_clues { get; set; }
        public DbSet<tx_agent> tx_agent { get; set; }
        public DbSet<tx_clue_image> tx_clue_image { get; set; }
        public DbSet<tx_settlement_detail> tx_settlement_detail { get; set; }
        public DbSet<dd_order> dd_order { get; set; }
        public DbSet<dd_order_serial> dd_order_serial { get; set; }
        public DbSet<bx_car_renewal_premium> bx_car_renewal_premium { get; set; }
        public DbSet<bx_quoteresult> bx_quoteresult { get; set; }
        public DbSet<dz_baodanxinxi> dz_baodanxinxi { get; set; }
        public DbSet<dz_correct_license_plate> dz_correct_license_plate { get; set; }
        public DbSet<dz_reconciliation> dz_reconciliation { get; set; }
    }
}
