//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bj_baodanxianzhong
    {
        public long Id { get; set; }
        public Nullable<long> BaoDanXinXiId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<double> CheSunBaoE { get; set; }
        public Nullable<double> SanZheBaoE { get; set; }
        public Nullable<double> DaoQiangBaoE { get; set; }
        public Nullable<double> SiJiBaoE { get; set; }
        public Nullable<double> ChengKeBaoE { get; set; }
        public Nullable<double> BoLiBaoE { get; set; }
        public Nullable<double> HuaHenBaoE { get; set; }
        public Nullable<double> TeYueBaoE { get; set; }
        public Nullable<double> SheShuiBaoE { get; set; }
        public Nullable<double> CheDengBaoE { get; set; }
        public Nullable<double> ZiRanBaoE { get; set; }
        public Nullable<double> CheSunBaoFei { get; set; }
        public Nullable<double> SanZheBaoFei { get; set; }
        public Nullable<double> DaoQiangBaoFei { get; set; }
        public Nullable<double> SiJiBaoFei { get; set; }
        public Nullable<double> ChengKeBaoFei { get; set; }
        public Nullable<double> BoLiBaoFei { get; set; }
        public Nullable<double> HuaHenBaoFei { get; set; }
        public Nullable<double> TeYueBaoFei { get; set; }
        public Nullable<double> SheShuiBaoFei { get; set; }
        public Nullable<double> CheDengBaoFei { get; set; }
        public Nullable<double> ZiRanBaoFei { get; set; }
        public Nullable<double> FeiYongBuChangBaoE { get; set; }
        public string FeiYongBuChangConfig { get; set; }
        public Nullable<double> FeiYongBuChangBaoFei { get; set; }
        public Nullable<double> XiuLiChangBaoE { get; set; }
        public string XiuLiChangConfig { get; set; }
        public Nullable<double> XiuLiChangBaoFei { get; set; }
        public Nullable<double> SheBeiSunShiBaoE { get; set; }
        public string SheBeiSunShiConfig { get; set; }
        public Nullable<double> SheBeiSunShiBaoFei { get; set; }
        public Nullable<double> HuoWuZeRenBaoE { get; set; }
        public Nullable<double> HuoWuZeRenBaoFei { get; set; }
        public Nullable<double> JingShenSunShiBaoE { get; set; }
        public Nullable<double> JingShenSunShiBaoFei { get; set; }
        public Nullable<double> BuJiMianJingShenSunShi { get; set; }
        public Nullable<double> SanFangTeYueBaoE { get; set; }
        public Nullable<double> SanFangTeYueBaoFei { get; set; }
        public Nullable<double> BuJiMianCheSun { get; set; }
        public Nullable<double> BuJiMianSanZhe { get; set; }
        public Nullable<double> BuJiMianDaoQiang { get; set; }
        public Nullable<double> BuJiMianRenYuan { get; set; }
        public Nullable<double> BuJiMianSiJi { get; set; }
        public Nullable<double> BuJiMianChengKe { get; set; }
        public Nullable<double> BuJiMianFuJian { get; set; }
        public Nullable<double> BuJiMianZiRan { get; set; }
        public Nullable<double> BuJiMianSheShui { get; set; }
        public Nullable<double> BuJiMianHuaHen { get; set; }
        public Nullable<double> BizTotal { get; set; }
        public Nullable<double> ForceTotal { get; set; }
        public Nullable<double> TaxTotal { get; set; }
        public string BizContent { get; set; }
        public string ForceContent { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<int> ChengKeBaoENum { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<int> FybcDays { get; set; }
        public Nullable<double> BuJiMianSheBeiSunShiBaoE { get; set; }
        public Nullable<double> BuJiMianSheBeiSunShiBaoFei { get; set; }
        public Nullable<int> JiaoQiang { get; set; }
        public Nullable<double> SanZheJieJiaRiBaoE { get; set; }
        public Nullable<double> SanZheJieJiaRiBaoFei { get; set; }
    }
}
