//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_address
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string Name { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<int> provinceId { get; set; }
        public Nullable<int> cityId { get; set; }
        public Nullable<int> areaId { get; set; }
        public Nullable<int> agentId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public bool isdefault { get; set; }
        public string province_name { get; set; }
        public string city_name { get; set; }
        public string area_name { get; set; }
    }
}
