//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_agent_ukey
    {
        public int id { get; set; }
        public Nullable<int> agent_id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<int> source { get; set; }
        public string dev_pin { get; set; }
        public string user_pin { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public string telnet { get; set; }
        public string telnet_name { get; set; }
        public string telnet_password { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> create_peopleId { get; set; }
        public string create_peopleName { get; set; }
        public string userName { get; set; }
        public Nullable<int> city_id { get; set; }
        public string agent_name { get; set; }
        public string ukey_company { get; set; }
        public Nullable<int> is_duizhang { get; set; }
        public Nullable<int> qudao_id { get; set; }
        public Nullable<int> is_interface { get; set; }
        public string macurl { get; set; }
        public Nullable<int> isusedeploy { get; set; }
        public Nullable<int> isurl { get; set; }
        public string InsuranceUserName { get; set; }
        public string ExcuteTimesByCountType { get; set; }
        public string ukey_operator { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public string backup_pwd_one { get; set; }
        public string backup_pwd_two { get; set; }
        public string backup_pwd_three { get; set; }
        public string org_name { get; set; }
        public int picc_ukey { get; set; }
        public int batch_get_policy { get; set; }
        public int deleted { get; set; }
        public int isQuote { get; set; }
        public int isSubmit { get; set; }
        public Nullable<int> MinDispatchTimes { get; set; }
        public Nullable<int> MaxDispatchMultiple { get; set; }
        public Nullable<int> isRenewal { get; set; }
        public string PingAnMobile { get; set; }
        public Nullable<sbyte> nettype { get; set; }
        public Nullable<int> isBiHuReserveChannel { get; set; }
        public Nullable<int> is_allow_channel_switch { get; set; }
        public int is_paic_api { get; set; }
        public string VersionType { get; set; }
    }
}
