//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_agent_setting
    {
        public int id { get; set; }
        public int agent_id { get; set; }
        public int reg_type { get; set; }
        public int settlement_type { get; set; }
        public int struct_type { get; set; }
        public int hide_carVIN { get; set; }
        public int hide_certificate { get; set; }
        public int can_multiple_quote { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public Nullable<int> TestState { get; set; }
        public Nullable<int> desensitization { get; set; }
        public Nullable<System.DateTime> contractStartDate { get; set; }
        public Nullable<int> hebao_insure { get; set; }
        public string store_name { get; set; }
        public string disclaimer_tips { get; set; }
        public Nullable<int> is_open_tuixiu { get; set; }
        public Nullable<int> sgc_phone_count { get; set; }
        public Nullable<int> is_checked_submit { get; set; }
    }
}
