//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_agent_bankcard
    {
        public int id { get; set; }
        public string bank_id { get; set; }
        public string bank_card_no { get; set; }
        public string bank_card_front { get; set; }
        public string bank_card_back { get; set; }
        public int agent_id { get; set; }
        public int deleted { get; set; }
        public System.DateTime create_time { get; set; }
    }
}
