//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_agent_busiuser
    {
        public int id { get; set; }
        public int busiuser_id { get; set; }
        public int agent_id { get; set; }
        public System.DateTime create_time { get; set; }
        public int is_used { get; set; }
        public int bx_busiusersetting_id { get; set; }
        public int bx_agent_config_id { get; set; }
        public int source { get; set; }
    }
}
