//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_agentpoint
    {
        public int id { get; set; }
        public int AgentId { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string WorkTimeStart { get; set; }
        public string WorkTimeEnd { get; set; }
        public bool Deleted { get; set; }
        public string WorkCycle { get; set; }
        public string WeChatAccountNum { get; set; }
        public string BankCardAccountNum { get; set; }
        public string AlipayAccountNum { get; set; }
        public Nullable<System.DateTime> ModifiTime { get; set; }
        public string BankCardAccountName { get; set; }
        public string BankCardName { get; set; }
        public string SubBranchCardName { get; set; }
        public bool IsShowForWebChat { get; set; }
        public Nullable<int> TopAgent { get; set; }
    }
}
