//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_busiuser
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> TotalScore { get; set; }
        public int RenewalScore { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<sbyte> IsAvailable { get; set; }
        public string Remark { get; set; }
        public Nullable<sbyte> IsAddSetting { get; set; }
        public Nullable<int> AgentID { get; set; }
    }
}
