//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_buid_activity
    {
        public int id { get; set; }
        public int B_Uid { get; set; }
        public int activity_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_name { get; set; }
    }
}
