//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_batchrenewal_erroritem
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public string ErrorMssage { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int RowIndex { get; set; }
        public string LicenseNo { get; set; }
        public string Mobile { get; set; }
        public string EngineNo { get; set; }
        public string MoldName { get; set; }
        public string RegisterDate { get; set; }
        public string VinNo { get; set; }
        public string CustomerName { get; set; }
        public string CategoryInfo { get; set; }
        public string MobileOther { get; set; }
        public string Remark { get; set; }
        public string LastYearSource { get; set; }
        public string ForceEndDate { get; set; }
        public string BizEndDate { get; set; }
        public string SalesManName { get; set; }
        public string SalesManAccount { get; set; }
        public string Intention_Remark { get; set; }
    }
}
