//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_busiusersetting
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> InsuranceType { get; set; }
        public Nullable<int> substation { get; set; }
        public string machineCode { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<sbyte> IsAvailable { get; set; }
        public string Remark { get; set; }
        public string tpuserId { get; set; }
        public string tppwd { get; set; }
        public string SaleChannel { get; set; }
    }
}
