//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_car_order
    {
        public long id { get; set; }
        public string order_num { get; set; }
        public Nullable<long> buid { get; set; }
        public Nullable<int> source { get; set; }
        public string insured_name { get; set; }
        public string contacts_name { get; set; }
        public Nullable<int> receipt_head { get; set; }
        public string receipt_title { get; set; }
        public Nullable<int> pay_type { get; set; }
        public Nullable<int> distribution_type { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> user_id { get; set; }
        public string openid { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<decimal> carriage_price { get; set; }
        public Nullable<decimal> insurance_price { get; set; }
        public Nullable<int> id_type { get; set; }
        public string id_num { get; set; }
        public string distribution_address { get; set; }
        public Nullable<int> order_status { get; set; }
        public string id_img_firs { get; set; }
        public string id_img_secd { get; set; }
        public Nullable<int> top_agent { get; set; }
        public string mobile { get; set; }
        public int addressid { get; set; }
        public Nullable<int> cur_agent { get; set; }
        public Nullable<int> pay_status { get; set; }
        public string distribution_name { get; set; }
        public string distribution_phone { get; set; }
        public Nullable<System.DateTime> distribution_time { get; set; }
        public Nullable<decimal> bizRate { get; set; }
        public string LicenseNo { get; set; }
        public Nullable<System.DateTime> GetOrderTime { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public string imageUrls { get; set; }
        public decimal forcerate { get; set; }
        public string order_email { get; set; }
        public string order_mobile { get; set; }
        public Nullable<System.DateTime> single_time { get; set; }
        public Nullable<decimal> bizCost { get; set; }
        public Nullable<decimal> forceCost { get; set; }
        public Nullable<int> CategoryInfoId { get; set; }
        public Nullable<int> zs_zuoxi_id { get; set; }
    }
}
