//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_companyrelation
    {
        public int id { get; set; }
        public int source { get; set; }
        public long flags { get; set; }
        public string name { get; set; }
        public string companyname { get; set; }
        public string companycode { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> isOpenedQuote { get; set; }
        public Nullable<int> isOpenedRenewal { get; set; }
        public string alias { get; set; }
    }
}
