//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_camera_detail
    {
        public int id { get; set; }
        public string camera_id { get; set; }
        public string car_plate { get; set; }
        public string park_id { get; set; }
        public string color { get; set; }
        public string start_time { get; set; }
        public string picture { get; set; }
        public string closeup_pic { get; set; }
        public Nullable<int> renewal_status { get; set; }
        public string renewal_message { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
    }
}
