//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_car_renewal_premium
    {
        public long Id { get; set; }
        public long car_renewal_id { get; set; }
        public string LicenseNo { get; set; }
        public string VinNo { get; set; }
        public string EngineNo { get; set; }
        public double CheSun { get; set; }
        public double SanZhe { get; set; }
        public double DaoQiang { get; set; }
        public double SiJi { get; set; }
        public double ChengKe { get; set; }
        public double BoLi { get; set; }
        public double HuaHen { get; set; }
        public double BuJiMianCheSun { get; set; }
        public double BuJiMianSanZhe { get; set; }
        public double BuJiMianDaoQiang { get; set; }
        public double BuJiMianRenYuan { get; set; }
        public double BuJiMianSiJi { get; set; }
        public double BuJiMianChengKe { get; set; }
        public double BuJiMianFuJia { get; set; }
        public double BuJiMianZiRan { get; set; }
        public double BuJiMianSheShui { get; set; }
        public double BuJiMianHuaHen { get; set; }
        public double BuJiMianSheBeiSunshi { get; set; }
        public double TeYue { get; set; }
        public double SheShui { get; set; }
        public double CheDeng { get; set; }
        public double ZiRan { get; set; }
        public double FeiYongBuChang { get; set; }
        public double XiuLiChang { get; set; }
        public double SheBeiSunShi { get; set; }
        public double HuoWuZeRen { get; set; }
        public double SanFangTeYue { get; set; }
        public double JingShenSunShi { get; set; }
        public double BuJiMianJingShenSunShi { get; set; }
        public double SanZheJieJiaRi { get; set; }
        public double BizPriceTotal { get; set; }
        public double ForcePriceTotal { get; set; }
        public double TaxPriceTotal { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
