//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_charge
    {
        public int id { get; set; }
        public Nullable<int> agent { get; set; }
        public Nullable<double> total_price { get; set; }
        public Nullable<double> unit_price { get; set; }
        public Nullable<int> total_count { get; set; }
        public Nullable<int> used_count { get; set; }
        public Nullable<int> charge_type { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<int> row_version { get; set; }
    }
}
