//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_city
    {
        public int id { get; set; }
        public string city_name { get; set; }
        public Nullable<int> cityId { get; set; }
        public Nullable<int> provinceid { get; set; }
        public string salesregion { get; set; }
        public string provincename { get; set; }
        public string provice_short_name { get; set; }
    }
}
