//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_consumer_review
    {
        public int id { get; set; }
        public string content { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> b_uid { get; set; }
        public Nullable<int> operatorId { get; set; }
        public string operatorName { get; set; }
        public Nullable<System.DateTime> next_review_date { get; set; }
        public Nullable<int> read_status { get; set; }
        public Nullable<int> result_status { get; set; }
        public Nullable<int> intentioncompany { get; set; }
        public int DefeatReasonId { get; set; }
        public string DefeatReasonContent { get; set; }
        public Nullable<System.DateTime> singletime { get; set; }
        public Nullable<System.DateTime> BizEndTime { get; set; }
        public bool IsDeleted { get; set; }
        public int ParentStatus { get; set; }
        public string xgAccount { get; set; }
        public int quote_receipt_reason_id { get; set; }
        public string quote_receipt_reason_content { get; set; }
        public Nullable<System.DateTime> to_store_time { get; set; }
        public int is_tostore { get; set; }
        public Nullable<int> operate_id { get; set; }
        public string operate_name { get; set; }
    }
}
