//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_distributed_history
    {
        public int id { get; set; }
        public long b_uid { get; set; }
        public int top_agent_id { get; set; }
        public int now_agent_id { get; set; }
        public int batch_id { get; set; }
        public int type_id { get; set; }
        public int operate_agent_id { get; set; }
        public System.DateTime create_time { get; set; }
    }
}
