//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_epolicy
    {
        public long id { get; set; }
        public Nullable<long> b_uid { get; set; }
        public Nullable<long> agent_id { get; set; }
        public Nullable<long> channel_id { get; set; }
        public Nullable<int> source { get; set; }
        public string biz_pno { get; set; }
        public string biz_tpno { get; set; }
        public string force_pno { get; set; }
        public string force_tpno { get; set; }
        public string license_no { get; set; }
        public string idcard_no { get; set; }
        public string hash { get; set; }
        public string key { get; set; }
        public Nullable<int> status { get; set; }
        public string msg { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
    }
}
