//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_gsc_renewal
    {
        public long Id { get; set; }
        public string InsureCompanyName { get; set; }
        public string PolicyNo { get; set; }
        public string Strdate { get; set; }
        public string Enddate { get; set; }
        public Nullable<int> IsCommerce { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public long B_uid { get; set; }
        public string Licenseno { get; set; }
    }
}
