//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_group_authen
    {
        public int id { get; set; }
        public int agentId { get; set; }
        public Nullable<int> authen_state { get; set; }
        public string cardholder { get; set; }
        public string card_id { get; set; }
        public string bank_card_number { get; set; }
        public string bank_name { get; set; }
        public string bank_son_name { get; set; }
        public string business_licence_url { get; set; }
        public string card_face_url { get; set; }
        public string card_reverse_url { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public Nullable<System.DateTime> audit_time { get; set; }
        public string audit_remark { get; set; }
        public string audit_user { get; set; }
        public string field_url { get; set; }
        public string bankcard_face_url { get; set; }
        public string bankcard_reverse_url { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string head_portrait { get; set; }
        public string mobile { get; set; }
        public Nullable<int> gender { get; set; }
        public string Dismissal { get; set; }
        public int is_complete_task { get; set; }
        public Nullable<System.DateTime> create_team_datetime { get; set; }
        public int level_id { get; set; }
        public Nullable<System.DateTime> last_balance_accounts_datetime { get; set; }
        public Nullable<int> TestState { get; set; }
        public string nickname { get; set; }
        public Nullable<int> header_id { get; set; }
        public string level_path { get; set; }
        public Nullable<int> top_agent { get; set; }
    }
}
