//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_hebaodianwei
    {
        public long id { get; set; }
        public Nullable<long> buid { get; set; }
        public Nullable<double> agent_biz_rate { get; set; }
        public Nullable<double> agent_force_rate { get; set; }
        public Nullable<double> agent_tax_rate { get; set; }
        public Nullable<double> zhike_biz_rate { get; set; }
        public Nullable<int> channel_id { get; set; }
        public Nullable<int> agent_id { get; set; }
        public Nullable<int> parent_agent_id { get; set; }
        public Nullable<double> system_biz_rate { get; set; }
        public Nullable<double> system_force_rate { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> channel_type { get; set; }
        public Nullable<double> agent_budian { get; set; }
        public string car_license { get; set; }
        public Nullable<int> source { get; set; }
    }
}
