//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_login_log
    {
        public int id { get; set; }
        public int agentId { get; set; }
        public string agent_name { get; set; }
        public string login_account { get; set; }
        public int manageruserId { get; set; }
        public System.DateTime login_time { get; set; }
        public string login_ip { get; set; }
        public Nullable<int> from_method { get; set; }
        public string browser_version { get; set; }
    }
}
