//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_message
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public int Msg_Type { get; set; }
        public Nullable<int> Agent_Id { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public Nullable<int> Msg_Status { get; set; }
        public Nullable<int> Msg_Level { get; set; }
        public Nullable<System.DateTime> Send_Time { get; set; }
        public int Create_Agent_Id { get; set; }
        public string Url { get; set; }
        public string License_No { get; set; }
        public Nullable<long> Buid { get; set; }
        public Nullable<int> ShowType { get; set; }
        public string ChannelAndScope { get; set; }
        public string MsgStatus { get; set; }
        public string MsgIntro { get; set; }
    }
}
