//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_msgindex
    {
        public long Id { get; set; }
        public int MsgId { get; set; }
        public int AgentId { get; set; }
        public int ReadStatus { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<System.DateTime> ReadTime { get; set; }
        public int Method { get; set; }
        public int Deleted { get; set; }
    }
}
