//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_notice_xb
    {
        public long id { get; set; }
        public string license_no { get; set; }
        public System.DateTime create_time { get; set; }
        public int stauts { get; set; }
        public Nullable<System.DateTime> last_force_end_date { get; set; }
        public Nullable<System.DateTime> Last_biz_end_date { get; set; }
        public Nullable<System.DateTime> next_force_start_date { get; set; }
        public Nullable<System.DateTime> next_biz_start_date { get; set; }
        public int source { get; set; }
        public int agent_id { get; set; }
        public Nullable<int> days { get; set; }
        public long b_uid { get; set; }
        public Nullable<int> day_num { get; set; }
    }
}
