//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_order_userinfo
    {
        public string LicenseNo { get; set; }
        public string OpenId { get; set; }
        public string CityCode { get; set; }
        public string EngineNo { get; set; }
        public string CarVIN { get; set; }
        public string MoldName { get; set; }
        public string RegisterDate { get; set; }
        public string Agent { get; set; }
        public string LicenseOwner { get; set; }
        public Nullable<int> CarType { get; set; }
        public Nullable<int> CarUsedType { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string JiaoQiangEndDate { get; set; }
        public string ShangYeEndDate { get; set; }
        public long Id { get; set; }
        public long OUId { get; set; }
        public Nullable<int> LastYearSource { get; set; }
        public string InsuredName { get; set; }
        public string InsuredMobile { get; set; }
        public string InsuredIdCard { get; set; }
        public string InsuredAddress { get; set; }
        public Nullable<int> RenewalType { get; set; }
        public Nullable<int> InsuredIdType { get; set; }
        public Nullable<int> OwnerIdCardType { get; set; }
        public string Email { get; set; }
        public Nullable<double> nonclaim_discount_rate { get; set; }
        public Nullable<int> last_year_acctimes { get; set; }
        public Nullable<double> last_year_claimamount { get; set; }
        public Nullable<int> last_year_claimtimes { get; set; }
        public string InsuredEmail { get; set; }
        public string HolderIdCard { get; set; }
        public string HolderName { get; set; }
        public string HolderMobile { get; set; }
        public string HolderAddress { get; set; }
        public Nullable<int> HolderIdType { get; set; }
        public string HolderEmail { get; set; }
        public string OwnerCertiAddress { get; set; }
    }
}
