//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_order
    {
        public long Id { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string LicenseNo { get; set; }
        public string Mobile { get; set; }
        public string OpenId { get; set; }
        public string CityCode { get; set; }
        public string RenewalIdNo { get; set; }
        public string EngineNo { get; set; }
        public string CarVIN { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<int> LastYearSource { get; set; }
        public string MoldName { get; set; }
        public string RegisterDate { get; set; }
        public string ApproxDate { get; set; }
        public string Address { get; set; }
        public string VehicleId { get; set; }
        public string StandardName { get; set; }
        public Nullable<int> NeedEngineNo { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> QuoteStatus { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> IsOrder { get; set; }
        public Nullable<int> IsReView { get; set; }
        public Nullable<int> JiSuanType { get; set; }
        public Nullable<int> IsService { get; set; }
        public Nullable<System.DateTime> ServiceTime { get; set; }
        public string Agent { get; set; }
        public Nullable<int> IsLastYear { get; set; }
        public string IdCard { get; set; }
        public string LicenseOwner { get; set; }
        public Nullable<int> IsTest { get; set; }
        public Nullable<double> BizTotal { get; set; }
        public Nullable<double> ForceTotal { get; set; }
        public Nullable<double> TaxTotal { get; set; }
        public Nullable<double> SaveAmount { get; set; }
        public Nullable<double> FinalPrice { get; set; }
        public Nullable<int> FuelCardNum { get; set; }
        public Nullable<int> CartridgeNum { get; set; }
        public Nullable<int> GlassyWaterNum { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> Buid { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> HongbaoId { get; set; }
        public Nullable<decimal> HongBaoAmount { get; set; }
        public Nullable<int> Datasource { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string QuoteBizCode { get; set; }
        public string QuoteJqCode { get; set; }
        public string NetRateDate { get; set; }
        public string BxUserName { get; set; }
        public Nullable<double> ApproxRate { get; set; }
        public string chudan_date { get; set; }
    }
}
