//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_order_submit_info
    {
        public long id { get; set; }
        public Nullable<long> b_uid { get; set; }
        public string license_no { get; set; }
        public string mobile { get; set; }
        public Nullable<int> source { get; set; }
        public string biz_tno { get; set; }
        public string biz_pno { get; set; }
        public Nullable<System.DateTime> biz_start_time { get; set; }
        public Nullable<System.DateTime> biz_end_time { get; set; }
        public string force_tno { get; set; }
        public string force_pno { get; set; }
        public Nullable<System.DateTime> force_start_time { get; set; }
        public Nullable<System.DateTime> force_end_time { get; set; }
        public Nullable<int> submit_status { get; set; }
        public string submit_result { get; set; }
        public Nullable<int> quote_status { get; set; }
        public string quote_result { get; set; }
        public Nullable<decimal> biz_rate { get; set; }
        public Nullable<decimal> force_rate { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string submit_result_toc { get; set; }
        public string quote_result_toc { get; set; }
        public Nullable<long> channel_id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<int> err_code { get; set; }
    }
}
