//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_quoteresult
    {
        public long Id { get; set; }
        public Nullable<long> B_Uid { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<double> CheSun { get; set; }
        public Nullable<double> SanZhe { get; set; }
        public Nullable<double> DaoQiang { get; set; }
        public Nullable<double> SiJi { get; set; }
        public Nullable<double> ChengKe { get; set; }
        public Nullable<double> BoLi { get; set; }
        public Nullable<double> HuaHen { get; set; }
        public Nullable<double> BuJiMianCheSun { get; set; }
        public Nullable<double> BuJiMianSanZhe { get; set; }
        public Nullable<double> BuJiMianDaoQiang { get; set; }
        public Nullable<double> BuJiMianRenYuan { get; set; }
        public Nullable<double> BuJiMianSiJi { get; set; }
        public Nullable<double> BuJiMianChengKe { get; set; }
        public Nullable<double> BuJiMianFuJian { get; set; }
        public Nullable<double> BuJiMianZiRan { get; set; }
        public Nullable<double> BuJiMianSheShui { get; set; }
        public Nullable<double> BuJiMianHuaHen { get; set; }
        public Nullable<double> TeYue { get; set; }
        public Nullable<double> SheShui { get; set; }
        public Nullable<double> CheDeng { get; set; }
        public Nullable<double> ZiRan { get; set; }
        public Nullable<double> SanZheJieJiaRi { get; set; }
        public Nullable<double> BizTotal { get; set; }
        public Nullable<double> ForceTotal { get; set; }
        public Nullable<double> TaxTotal { get; set; }
        public string BizContent { get; set; }
        public string ForceContent { get; set; }
        public Nullable<double> SavedAmount { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<System.DateTime> BizStartDate { get; set; }
        public Nullable<System.DateTime> ForceStartDate { get; set; }
        public Nullable<double> HcSheBeiSunshi { get; set; }
        public Nullable<double> HcHuoWuZeRen { get; set; }
        public Nullable<double> HcFeiYongBuChang { get; set; }
        public Nullable<double> HcJingShenSunShi { get; set; }
        public Nullable<double> BuJiMianJingShenSunShi { get; set; }
        public Nullable<double> HcSanFangTeYue { get; set; }
        public Nullable<double> HcXiuLiChang { get; set; }
        public string InsuredName { get; set; }
        public string InsuredIdCard { get; set; }
        public Nullable<int> InsuredIdType { get; set; }
        public string InsuredMobile { get; set; }
        public string HolderName { get; set; }
        public string HolderIdCard { get; set; }
        public Nullable<int> HolderIdType { get; set; }
        public string HolderMobile { get; set; }
        public Nullable<decimal> RateFactor1 { get; set; }
        public Nullable<decimal> RateFactor2 { get; set; }
        public Nullable<decimal> RateFactor3 { get; set; }
        public Nullable<decimal> RateFactor4 { get; set; }
        public Nullable<int> HcXiuLiChangType { get; set; }
        public Nullable<double> CheSunBE { get; set; }
        public Nullable<double> ZiRanBE { get; set; }
        public Nullable<double> DaoQiangBE { get; set; }
        public Nullable<double> BuJiMianSheBeiSunshi { get; set; }
        public Nullable<int> HcFeiYongBuChangDays { get; set; }
        public Nullable<decimal> PingAnScore { get; set; }
        public Nullable<decimal> TotalRate { get; set; }
        public Nullable<decimal> expected_loss_rate { get; set; }
        public Nullable<decimal> biz_expected_loss_rate { get; set; }
        public string HeckCode { get; set; }
        public string QryCde { get; set; }
        public Nullable<decimal> NewRate { get; set; }
        public Nullable<decimal> BizCpicScore { get; set; }
        public Nullable<decimal> TotalCpicScore { get; set; }
        public Nullable<decimal> TotalEcompensationRate { get; set; }
        public Nullable<decimal> ActualDiscounts { get; set; }
    }
}
