//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_quotereq_carinfo
    {
        public long id { get; set; }
        public long b_uid { get; set; }
        public Nullable<int> seat_count { get; set; }
        public Nullable<decimal> exhaust_scale { get; set; }
        public Nullable<decimal> car_equ_quality { get; set; }
        public Nullable<decimal> car_ton_count { get; set; }
        public Nullable<int> fuel_type { get; set; }
        public Nullable<int> proof_type { get; set; }
        public Nullable<int> clause_type { get; set; }
        public Nullable<int> car_type { get; set; }
        public Nullable<int> car_used_type { get; set; }
        public Nullable<int> license_color { get; set; }
        public Nullable<int> is_newcar { get; set; }
        public Nullable<int> is_public { get; set; }
        public Nullable<int> is_lastnewcar { get; set; }
        public Nullable<double> special_rate { get; set; }
        public Nullable<double> run_miles { get; set; }
        public Nullable<System.DateTime> biz_start_date { get; set; }
        public Nullable<System.DateTime> force_start_date { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<System.DateTime> transfer_date { get; set; }
        public string auto_model_code { get; set; }
        public string e_mail { get; set; }
        public Nullable<int> auto_model_code_source { get; set; }
        public string pa_remark { get; set; }
        public Nullable<decimal> co_real_value { get; set; }
        public Nullable<System.DateTime> biz_end_date { get; set; }
        public Nullable<System.DateTime> force_end_date { get; set; }
        public Nullable<int> IsShortQuote { get; set; }
        public Nullable<decimal> PriceT { get; set; }
        public Nullable<int> seatflag { get; set; }
        public Nullable<int> is_truck { get; set; }
        public string drivlicense_cartype_name { get; set; }
        public string drivlicense_cartype_value { get; set; }
        public string Operator { get; set; }
        public string RepairCode { get; set; }
        public string Ownership { get; set; }
        public string ChannelCode { get; set; }
        public string account_relation { get; set; }
        public int pingan_quote_type { get; set; }
        public long moldcode_company { get; set; }
        public Nullable<decimal> special_discount_application { get; set; }
        public string ownerOrg { get; set; }
        public string policyOrg { get; set; }
        public string renBaoRateSplit { get; set; }
        public Nullable<int> is_loans { get; set; }
        public Nullable<decimal> ActualDiscounts { get; set; }
        public string VehicleAlias { get; set; }
        public string VehicleYear { get; set; }
        public Nullable<decimal> ActualSalesForceRatio { get; set; }
        public Nullable<decimal> ActualSalesBizRatio { get; set; }
        public Nullable<decimal> ActualDtaryForceRatio { get; set; }
        public Nullable<decimal> ActualDtaryBizRatio { get; set; }
        public Nullable<decimal> ChannelRate { get; set; }
        public Nullable<decimal> SubmitRate { get; set; }
        public string TrCausesWhy { get; set; }
        public string actualdiscounts_ratio { get; set; }
        public Nullable<int> IsTempStorage { get; set; }
        public Nullable<int> IsPaFloorPrice { get; set; }
        public string DriverCard { get; set; }
        public string DriverCardType { get; set; }
    }
}
