//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_quoterenewal_agent_config
    {
        public int Id { get; set; }
        public int AgentId { get; set; }
        public int LimitTotal { get; set; }
        public int LimitSamePerCarHour { get; set; }
        public int LimitPerMinute { get; set; }
        public int LimitPerHour { get; set; }
        public int LimitPerDay { get; set; }
        public int LimitPerWeek { get; set; }
        public int LimitTotalMinute { get; set; }
        public int LimitTotalHour { get; set; }
        public int LimitTotalDay { get; set; }
        public int BatchrenewalTotalCount { get; set; }
        public bool Deleted { get; set; }
        public int AccessibilityStartTime { get; set; }
        public int AccessibilityEndTime { get; set; }
    }
}
