//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_quotehistory_related
    {
        public long id { get; set; }
        public long b_uid { get; set; }
        public long groupspan { get; set; }
        public string ower_name { get; set; }
        public Nullable<int> ower_id_type { get; set; }
        public string ower_id_card { get; set; }
        public Nullable<int> ower_sex { get; set; }
        public string ower_nation { get; set; }
        public Nullable<System.DateTime> ower_birthday { get; set; }
        public string ower_address { get; set; }
        public Nullable<System.DateTime> ower_certi_start_date { get; set; }
        public Nullable<System.DateTime> ower_certi_end_date { get; set; }
        public string ower_authority { get; set; }
        public string ower_mobile { get; set; }
        public string ower_email { get; set; }
        public string holder_name { get; set; }
        public Nullable<int> holder_id_type { get; set; }
        public string holder_id_card { get; set; }
        public Nullable<int> holder_sex { get; set; }
        public string holder_nation { get; set; }
        public Nullable<System.DateTime> holder_birthday { get; set; }
        public string holder_address { get; set; }
        public Nullable<System.DateTime> holder_certi_start_date { get; set; }
        public Nullable<System.DateTime> holder_certi_end_date { get; set; }
        public string holder_authority { get; set; }
        public string holder_mobile { get; set; }
        public string holder_email { get; set; }
        public string insured_name { get; set; }
        public Nullable<int> insured_id_type { get; set; }
        public string insured_id_card { get; set; }
        public Nullable<int> insured_sex { get; set; }
        public string insured_nation { get; set; }
        public Nullable<System.DateTime> insured_birthday { get; set; }
        public string insured_address { get; set; }
        public Nullable<System.DateTime> insured_certi_start_date { get; set; }
        public Nullable<System.DateTime> insured_certi_end_date { get; set; }
        public string insured_authority { get; set; }
        public string insured_mobile { get; set; }
        public string insured_email { get; set; }
        public System.DateTime create_time { get; set; }
        public System.DateTime update_time { get; set; }
    }
}
