//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_quoteresult_carinfo
    {
        public long id { get; set; }
        public long b_uid { get; set; }
        public Nullable<int> source { get; set; }
        public string engine_no { get; set; }
        public string vin_no { get; set; }
        public string mold_name { get; set; }
        public Nullable<System.DateTime> register_date { get; set; }
        public string owner_idno { get; set; }
        public string license_owner { get; set; }
        public Nullable<int> owner_idno_type { get; set; }
        public Nullable<int> license_type { get; set; }
        public Nullable<int> car_type { get; set; }
        public Nullable<int> car_used_type { get; set; }
        public Nullable<int> seat_count { get; set; }
        public Nullable<decimal> exhaust_scale { get; set; }
        public Nullable<decimal> car_equ_quality { get; set; }
        public Nullable<decimal> car_ton_count { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public Nullable<int> fuel_type { get; set; }
        public Nullable<int> proof_type { get; set; }
        public Nullable<int> license_color { get; set; }
        public Nullable<int> clause_type { get; set; }
        public Nullable<int> run_region { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string auto_model_code { get; set; }
        public string VehicleYear { get; set; }
        public string Cardepict { get; set; }
        public string VehicleAlias { get; set; }
        public string risk { get; set; }
        public string IsZhuanXubao { get; set; }
        public string SyVehicleClaimType { get; set; }
        public string JqVehicleClaimType { get; set; }
        public string VehicleStyle { get; set; }
    }
}
