//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_report_claim
    {
        public long id { get; set; }
        public string LicenseNo { get; set; }
        public string AccidentPlace { get; set; }
        public string AccidentPsss { get; set; }
        public string DriverName { get; set; }
        public Nullable<int> IsCommerce { get; set; }
        public Nullable<int> IsOwners { get; set; }
        public Nullable<int> IsThreecCar { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
