//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_reconciliation
    {
        public int id { get; set; }
        public Nullable<long> b_uid { get; set; }
        public string order_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<double> insurance_price { get; set; }
        public Nullable<int> insurance_type { get; set; }
        public Nullable<double> tax_price { get; set; }
        public string licenseNo { get; set; }
        public string create_date { get; set; }
        public string issuing_date { get; set; }
        public Nullable<int> create_people_id { get; set; }
        public string create_people_name { get; set; }
        public string user_name { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<double> rate_price { get; set; }
        public Nullable<int> rate_type { get; set; }
        public string chudan_date { get; set; }
        public Nullable<double> fapiao_rate { get; set; }
        public Nullable<double> fapiao_peice { get; set; }
        public Nullable<double> budian { get; set; }
        public Nullable<double> fanyong { get; set; }
        public Nullable<double> system_rate { get; set; }
        public Nullable<double> tax_rate { get; set; }
        public Nullable<double> force_rate { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> koudian { get; set; }
        public Nullable<int> agent_id { get; set; }
        public Nullable<double> koudian_price { get; set; }
        public Nullable<double> jinfei { get; set; }
        public Nullable<int> isShow { get; set; }
    }
}
