//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_userinfo_expand
    {
        public int id { get; set; }
        public long b_uid { get; set; }
        public int is_temp_mobile { get; set; }
        public int is_temp_email { get; set; }
        public System.DateTime update_time { get; set; }
        public int delete_type { get; set; }
        public System.DateTime delete_time { get; set; }
        public Nullable<int> CarOwnerStatus { get; set; }
        public string CameraId { get; set; }
    }
}
