//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_userinfo_renewal_info
    {
        public int id { get; set; }
        public Nullable<long> b_uid { get; set; }
        public Nullable<int> sa_id { get; set; }
        public string sa_name { get; set; }
        public Nullable<int> xubao_id { get; set; }
        public string xubao_name { get; set; }
        public Nullable<int> client_intention { get; set; }
        public string remark { get; set; }
        public System.DateTime create_time { get; set; }
        public string client_mobile { get; set; }
        public string client_name { get; set; }
        public string intention_remark { get; set; }
        public Nullable<int> intentioncompany { get; set; }
        public Nullable<int> result_status { get; set; }
        public int CustomerType { get; set; }
        public string client_mobile_other { get; set; }
        public string client_address { get; set; }
        public int is_client_mobile { get; set; }
        public string TagId { get; set; }
    }
}
