//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_zc_team_task_setting
    {
        public int id { get; set; }
        public int order_count { get; set; }
        public int agent_count { get; set; }
        public int is_delete { get; set; }
        public System.DateTime create_time { get; set; }
        public int top_agent { get; set; }
    }
}
