//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_order_quoteresult
    {
        public long Id { get; set; }
        public long B_Uid { get; set; }
        public long dd_order_id { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<double> CheSun { get; set; }
        public Nullable<double> SanZhe { get; set; }
        public Nullable<double> DaoQiang { get; set; }
        public Nullable<double> SiJi { get; set; }
        public Nullable<double> ChengKe { get; set; }
        public Nullable<double> BoLi { get; set; }
        public Nullable<double> HuaHen { get; set; }
        public Nullable<double> BuJiMianCheSun { get; set; }
        public Nullable<double> BuJiMianSanZhe { get; set; }
        public Nullable<double> BuJiMianDaoQiang { get; set; }
        public Nullable<double> BuJiMianRenYuan { get; set; }
        public Nullable<double> BuJiMianSiJi { get; set; }
        public Nullable<double> BuJiMianChengKe { get; set; }
        public Nullable<double> BuJiMianFuJian { get; set; }
        public Nullable<double> BuJiMianZiRan { get; set; }
        public Nullable<double> BuJiMianSheShui { get; set; }
        public Nullable<double> BuJiMianHuaHen { get; set; }
        public Nullable<double> TeYue { get; set; }
        public Nullable<double> SheShui { get; set; }
        public Nullable<double> CheDeng { get; set; }
        public Nullable<double> ZiRan { get; set; }
        public Nullable<double> BizTotal { get; set; }
        public Nullable<double> ForceTotal { get; set; }
        public Nullable<double> TaxTotal { get; set; }
        public string BizContent { get; set; }
        public string ForceContent { get; set; }
        public Nullable<double> SavedAmount { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<System.DateTime> BizStartDate { get; set; }
        public Nullable<System.DateTime> ForceStartDate { get; set; }
        public Nullable<double> HcSheBeiSunshi { get; set; }
        public Nullable<double> HcHuoWuZeRen { get; set; }
        public Nullable<double> HcFeiYongBuChang { get; set; }
        public Nullable<double> HcJingShenSunShi { get; set; }
        public Nullable<double> BuJiMianJingShenSunShi { get; set; }
        public Nullable<double> HcSanFangTeYue { get; set; }
        public Nullable<double> HcXiuLiChang { get; set; }
        public string InsuredName { get; set; }
        public string InsuredIdCard { get; set; }
        public Nullable<int> InsuredIdType { get; set; }
        public string InsuredMobile { get; set; }
        public string HolderName { get; set; }
        public string HolderIdCard { get; set; }
        public Nullable<int> HolderIdType { get; set; }
        public string HolderMobile { get; set; }
        public Nullable<decimal> RateFactor1 { get; set; }
        public Nullable<decimal> RateFactor2 { get; set; }
        public Nullable<decimal> RateFactor3 { get; set; }
        public Nullable<decimal> RateFactor4 { get; set; }
        public Nullable<int> HcXiuLiChangType { get; set; }
        public Nullable<double> CheSunBE { get; set; }
        public Nullable<double> ZiRanBE { get; set; }
        public Nullable<double> DaoQiangBE { get; set; }
        public Nullable<double> BuJiMianSheBeiSunshi { get; set; }
        public Nullable<int> HcFeiYongBuChangDays { get; set; }
        public Nullable<decimal> PingAnScore { get; set; }
        public Nullable<decimal> TotalRate { get; set; }
        public System.DateTime update_time { get; set; }
        public System.DateTime create_time { get; set; }
        public int biz_claim_count { get; set; }
        public int force_claim_count { get; set; }
        public Nullable<decimal> expected_loss_rate { get; set; }
        public Nullable<decimal> biz_expected_loss_rate { get; set; }
        public string RegisterDate { get; set; }
        public string CarVIN { get; set; }
        public string EngineNo { get; set; }
        public Nullable<System.DateTime> biz_end_time { get; set; }
        public Nullable<System.DateTime> force_end_time { get; set; }
        public string biz_pno { get; set; }
        public string force_pno { get; set; }
        public Nullable<int> submit_status { get; set; }
        public Nullable<int> quote_status { get; set; }
        public string submit_result { get; set; }
        public string quote_result { get; set; }
        public string auto_model_code { get; set; }
        public Nullable<System.DateTime> biz_start_date { get; set; }
        public Nullable<System.DateTime> force_start_date { get; set; }
        public Nullable<int> car_used_type { get; set; }
        public Nullable<decimal> PriceT { get; set; }
        public Nullable<int> seat_count { get; set; }
        public Nullable<double> SanZheJieJiaRi { get; set; }
    }
}
