//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_order
    {
        public long id { get; set; }
        public string order_num { get; set; }
        public string order_guid { get; set; }
        public int delivery_method { get; set; }
        public string delivery_address { get; set; }
        public string delivery_contacts { get; set; }
        public string delivery_contacts_mobile { get; set; }
        public int pay_type { get; set; }
        public long b_uid { get; set; }
        public System.DateTime update_time { get; set; }
        public System.DateTime create_time { get; set; }
        public int agent_id { get; set; }
        public string agent_name { get; set; }
        public Nullable<int> issuing_people_id { get; set; }
        public string issuing_people_name { get; set; }
        public Nullable<int> delivery_type { get; set; }
        public string remark { get; set; }
        public int order_type { get; set; }
        public Nullable<System.DateTime> order_lapse_time { get; set; }
        public Nullable<System.DateTime> verification_code_create_time { get; set; }
        public Nullable<System.DateTime> pay_code_create_time { get; set; }
        public System.DateTime issue_time { get; set; }
        public string pay_code_url { get; set; }
        public string licenseno { get; set; }
        public int source { get; set; }
        public int consumer_pay_status { get; set; }
        public int insurance_company_pay_status { get; set; }
        public int verification_code_status { get; set; }
        public int quote_city_id { get; set; }
        public int quote_config_id { get; set; }
        public string force_tno { get; set; }
        public string biz_tno { get; set; }
        public int insure_year { get; set; }
        public int get_order_method { get; set; }
        public string preferential { get; set; }
        public Nullable<double> total_amount { get; set; }
        public Nullable<double> receivable_amount { get; set; }
        public Nullable<double> purchase_amount { get; set; }
        public Nullable<decimal> force_rate { get; set; }
        public Nullable<decimal> biz_rate { get; set; }
        public int is_change_related { get; set; }
        public string MoldName { get; set; }
        public Nullable<System.DateTime> LastForceEndDate { get; set; }
        public Nullable<System.DateTime> LastBizEndDate { get; set; }
        public int payee { get; set; }
        public int delivery_address_id { get; set; }
        public int pay_way_id { get; set; }
        public int PayMent { get; set; }
        public string PayMentRemark { get; set; }
        public string ax_order_num { get; set; }
        public Nullable<int> IsCollection { get; set; }
        public Nullable<int> CarOwnerId { get; set; }
        public Nullable<int> zs_zuoxi_id { get; set; }
        public string zs_zuoxi_name { get; set; }
        public string biz_pno { get; set; }
        public string force_pno { get; set; }
        public string transaction_no { get; set; }
        public string serial_no { get; set; }
        public Nullable<System.DateTime> pay_time { get; set; }
        public Nullable<System.DateTime> pay_biz_time { get; set; }
        public Nullable<System.DateTime> pay_force_time { get; set; }
    }
}
