//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_order_collection
    {
        public int id { get; set; }
        public string order_num { get; set; }
        public string licenseno { get; set; }
        public string biz_tno { get; set; }
        public string force_tno { get; set; }
        public string verify_code { get; set; }
        public long is_out { get; set; }
        public long status { get; set; }
        public System.DateTime update_time { get; set; }
        public System.DateTime creat_time { get; set; }
    }
}
