//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_order_commission
    {
        public int id { get; set; }
        public long order_id { get; set; }
        public int cur_agent { get; set; }
        public double money { get; set; }
        public double credit { get; set; }
        public string license_no { get; set; }
        public string policy_no { get; set; }
        public sbyte policy_type { get; set; }
        public sbyte commission_type { get; set; }
        public sbyte status { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<int> withdrawal_id { get; set; }
        public Nullable<int> withdrawal_status { get; set; }
        public Nullable<int> child_agent { get; set; }
        public Nullable<int> child_agent_grade { get; set; }
        public Nullable<int> team_reward_proportion { get; set; }
        public Nullable<double> net_premium { get; set; }
    }
}
