//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_order_serial
    {
        public int id { get; set; }
        public string order_num { get; set; }
        public string pay_url { get; set; }
        public Nullable<System.DateTime> failure_time { get; set; }
        public string notice_no { get; set; }
        public Nullable<System.DateTime> payment_time { get; set; }
        public Nullable<double> amount { get; set; }
        public string currency { get; set; }
        public string pay_status { get; set; }
        public string customer_name { get; set; }
        public string licenseno { get; set; }
        public string serialr_no { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> isout { get; set; }
    }
}
