//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_order_savequote
    {
        public long Id { get; set; }
        public long B_Uid { get; set; }
        public long dd_order_id { get; set; }
        public Nullable<double> CheSun { get; set; }
        public Nullable<double> SanZhe { get; set; }
        public Nullable<double> DaoQiang { get; set; }
        public Nullable<double> SiJi { get; set; }
        public Nullable<double> ChengKe { get; set; }
        public Nullable<double> BoLi { get; set; }
        public Nullable<double> HuaHen { get; set; }
        public Nullable<double> BuJiMianCheSun { get; set; }
        public Nullable<double> BuJiMianSanZhe { get; set; }
        public Nullable<double> BuJiMianDaoQiang { get; set; }
        public Nullable<double> BuJiMianRenYuan { get; set; }
        public Nullable<double> BuJiMianSiJi { get; set; }
        public Nullable<double> BuJiMianChengKe { get; set; }
        public Nullable<double> BuJiMianFuJian { get; set; }
        public Nullable<double> BuJiMianZiRan { get; set; }
        public Nullable<double> BuJiMianSheShui { get; set; }
        public Nullable<double> BuJiMianHuaHen { get; set; }
        public Nullable<double> TeYue { get; set; }
        public Nullable<double> SheShui { get; set; }
        public Nullable<double> CheDeng { get; set; }
        public Nullable<double> ZiRan { get; set; }
        public int IsRenewal { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> JiaoQiang { get; set; }
        public Nullable<System.DateTime> BizStartDate { get; set; }
        public Nullable<double> HcSheBeiSunshi { get; set; }
        public string SheBeiSunShiConfig { get; set; }
        public Nullable<double> HcHuoWuZeRen { get; set; }
        public Nullable<double> HcFeiYongBuChang { get; set; }
        public Nullable<int> FeiYongBuChangDays { get; set; }
        public string FeiYongBuChangConfig { get; set; }
        public Nullable<double> HcJingShenSunShi { get; set; }
        public Nullable<double> BuJiMianJingShenSunShi { get; set; }
        public Nullable<double> HcSanFangTeYue { get; set; }
        public Nullable<double> HcXiuLiChang { get; set; }
        public string XiuLiChangConfig { get; set; }
        public Nullable<int> HcXiuLiChangType { get; set; }
        public Nullable<decimal> co_real_value { get; set; }
        public Nullable<double> BuJiMianSheBeiSunshi { get; set; }
        public System.DateTime update_time { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<double> SanZheJieJiaRi { get; set; }
    }
}
