//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_pay_bank
    {
        public int id { get; set; }
        public int city_id { get; set; }
        public string bank_name { get; set; }
        public string bank_id { get; set; }
        public Nullable<int> invalid { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
    }
}
