//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dz_baodanxinxi
    {
        public long Id { get; set; }
        public string CarOwner { get; set; }
        public Nullable<System.DateTime> BizStartDate { get; set; }
        public Nullable<System.DateTime> BizEndDate { get; set; }
        public string BizNum { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> ForceStartDate { get; set; }
        public Nullable<System.DateTime> ForceEndDate { get; set; }
        public string ForceNum { get; set; }
        public Nullable<System.DateTime> ChargesDate { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string InsuredName { get; set; }
        public Nullable<int> InsureSex { get; set; }
        public Nullable<System.DateTime> InsureBirth { get; set; }
        public string InsureIdType { get; set; }
        public string InsureIdNum { get; set; }
        public string CarLicense { get; set; }
        public string CarBrandModel { get; set; }
        public string CarEngineNo { get; set; }
        public string CarVIN { get; set; }
        public string CarDisplacement { get; set; }
        public string CarUsedType { get; set; }
        public string CarOwnerType { get; set; }
        public Nullable<System.DateTime> CarRegisterDate { get; set; }
        public string CarType { get; set; }
        public string CarTravelArea { get; set; }
        public string CarSeated { get; set; }
        public Nullable<decimal> CarPrice { get; set; }
        public string CarAvgMileage { get; set; }
        public Nullable<int> AgentId { get; set; }
        public string AgentName { get; set; }
        public string PrinterName { get; set; }
        public Nullable<int> PrinterId { get; set; }
        public Nullable<long> ChannelId { get; set; }
        public string ChannelName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> OperatingID { get; set; }
        public string OperatingName { get; set; }
        public Nullable<double> BizRate { get; set; }
        public Nullable<double> ForceRate { get; set; }
        public Nullable<double> BizPrice { get; set; }
        public Nullable<double> ForcePrice { get; set; }
        public Nullable<double> TaxPrice { get; set; }
        public Nullable<int> IsSuccess { get; set; }
        public string QuDaoMingCheng { get; set; }
        public Nullable<int> SaleId { get; set; }
        public string SaleName { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string OwnerName { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> IsNewCar { get; set; }
        public Nullable<int> IsGroup { get; set; }
        public Nullable<System.DateTime> ForcPrintDate { get; set; }
        public Nullable<int> UKeyId { get; set; }
        public Nullable<int> is_duizhang { get; set; }
        public string ErrorMessgae { get; set; }
        public Nullable<int> BaoDanType { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> ForceInputDate { get; set; }
        public Nullable<System.DateTime> ForceArrivalDate { get; set; }
        public string PolicyHoderName { get; set; }
        public string PolicyHoderIdType { get; set; }
        public string PolicyHoderIdNum { get; set; }
        public string PolicyHoderMoblie { get; set; }
        public string InsureMoblie { get; set; }
        public Nullable<double> NonClaimRate { get; set; }
        public Nullable<double> MultiDiscountRate { get; set; }
        public Nullable<double> AvgMileRate { get; set; }
        public Nullable<double> RiskRate { get; set; }
        public string CarEquQuality { get; set; }
        public string CarTonCount { get; set; }
        public string CarLicenseType { get; set; }
        public string CarOwnerIdNo { get; set; }
        public string CarOwnerIdNoType { get; set; }
        public string CarLicenseColor { get; set; }
        public string CarClauseType { get; set; }
        public string CarFuelType { get; set; }
        public string CarProofType { get; set; }
        public string InsureIdTypeValue { get; set; }
        public string PolicyHoderIdTypeValue { get; set; }
        public string CarOwnerIdNoTypeValue { get; set; }
        public string CarUsedTypeValue { get; set; }
        public string CarTypeValue { get; set; }
        public string CarTravelAreaValue { get; set; }
        public string CarLicenseTypeValue { get; set; }
        public string CarLicenseColorValue { get; set; }
        public string ClauseTypeValue { get; set; }
        public string CarFuelTypeValue { get; set; }
        public string CarProofTypeValue { get; set; }
        public string SubCarType { get; set; }
        public string SubCarTypeValue { get; set; }
        public string BiztNo { get; set; }
        public string ForcetNo { get; set; }
        public Nullable<int> ReturnInsured { get; set; }
        public string LastPolicyNo { get; set; }
        public string PolicyPrintNo { get; set; }
        public Nullable<System.DateTime> SigningDate { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<System.DateTime> CardDate { get; set; }
        public string OwnerPeople { get; set; }
        public string VehiclePeople { get; set; }
        public string BatchNo { get; set; }
        public string QuDaoCode { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<int> ServiceLife { get; set; }
        public Nullable<int> BaoDanNature { get; set; }
        public Nullable<int> LastYearAccTimes { get; set; }
        public Nullable<double> LastYearClaimAmount { get; set; }
        public Nullable<int> LastYearClaimTimes { get; set; }
        public string NoDefendedYear { get; set; }
        public Nullable<int> CurrentYearClaimTimes { get; set; }
        public string OwnerEmail { get; set; }
        public string InsuredEmail { get; set; }
        public string PolicyHoderEmail { get; set; }
        public Nullable<System.DateTime> ForceChargesDate { get; set; }
        public string Guid { get; set; }
        public string OwnerMobile { get; set; }
        public string LastBizpNo { get; set; }
        public string LastForcepNo { get; set; }
        public Nullable<double> IncludeTaxTotal { get; set; }
        public Nullable<double> CleanTotal { get; set; }
        public Nullable<double> ShuiJinTotal { get; set; }
        public string DzSaleName { get; set; }
        public string DzPracticeNo { get; set; }
        public Nullable<int> DataSource { get; set; }
        public Nullable<sbyte> IsHaveLicenseNo { get; set; }
        public decimal co_real_value { get; set; }
        public string Organization { get; set; }
    }
}
