//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dz_correct_license_plate
    {
        public int id { get; set; }
        public string license_no { get; set; }
        public string apply_no { get; set; }
        public string force_check_no { get; set; }
        public string biz_check_no { get; set; }
        public string car_vin { get; set; }
        public string car_engine_no { get; set; }
        public string car_brand_model { get; set; }
        public string car_owner { get; set; }
        public Nullable<System.DateTime> car_register_date { get; set; }
        public Nullable<System.DateTime> biz_end_date { get; set; }
        public Nullable<System.DateTime> force_end_date { get; set; }
        public int source { get; set; }
        public string biz_pno { get; set; }
        public string force_pno { get; set; }
        public int agent_id { get; set; }
        public string agent_name { get; set; }
        public short state { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> upadte_time { get; set; }
        public string guid { get; set; }
        public int bu_id { get; set; }
        public Nullable<int> top_agent_id { get; set; }
        public string top_agent_name { get; set; }
        public Nullable<int> parent_agent_id { get; set; }
        public string parent_agent_name { get; set; }
    }
}
