//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dz_reconciliation
    {
        public int id { get; set; }
        public string order_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<double> insurance_price { get; set; }
        public Nullable<int> insurance_type { get; set; }
        public Nullable<double> tax_price { get; set; }
        public string licenseNo { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string issuing_date { get; set; }
        public Nullable<int> create_people_id { get; set; }
        public string create_people_name { get; set; }
        public string user_name { get; set; }
        public Nullable<int> agent_id { get; set; }
        public Nullable<int> print_people_id { get; set; }
        public string Print_people_name { get; set; }
        public Nullable<int> qudao_id { get; set; }
        public string qudao_name { get; set; }
        public Nullable<int> sale_id { get; set; }
        public string sale_name { get; set; }
        public string agent_name { get; set; }
        public Nullable<int> agent_type { get; set; }
        public Nullable<int> ower_id { get; set; }
        public string ower_name { get; set; }
        public Nullable<int> baodanxinxi_id { get; set; }
        public Nullable<double> agent_receivable_price { get; set; }
        public Nullable<int> ukey_id { get; set; }
        public string guid { get; set; }
        public Nullable<int> bao_dan_type { get; set; }
        public Nullable<int> agent_pay_type { get; set; }
        public string agent_remarks { get; set; }
        public Nullable<int> agent_discount_object { get; set; }
        public Nullable<int> baoDan_nature { get; set; }
        public Nullable<double> agent_bizRate_discount { get; set; }
        public Nullable<double> agent_forceRate_discount { get; set; }
        public Nullable<int> agent_premiumType { get; set; }
        public Nullable<int> company_type { get; set; }
        public Nullable<double> company_bizRate_discount { get; set; }
        public Nullable<double> company_forceRate_discount { get; set; }
        public Nullable<int> company_FeeType { get; set; }
        public Nullable<double> company_receivable_amount { get; set; }
        public Nullable<double> company_actual_amount { get; set; }
        public Nullable<double> agent_receivable_baofei { get; set; }
        public Nullable<double> agent_actual_baofei { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<double> agent_discount_amount { get; set; }
        public int source { get; set; }
        public Nullable<double> profit { get; set; }
        public Nullable<double> agent_receivable_premium { get; set; }
        public string payment_type { get; set; }
        public double admini_rote { get; set; }
        public double admini_amount { get; set; }
        public double admin_total_amount { get; set; }
        public double settlement_amount { get; set; }
        public string CarVIN { get; set; }
        public Nullable<int> organization_rebate_rate { get; set; }
        public Nullable<double> actual_commission_rate { get; set; }
        public Nullable<int> company_billing_rate { get; set; }
        public string ukey_name { get; set; }
        public Nullable<System.DateTime> signing_date { get; set; }
        public Nullable<int> HQ_interest_rate { get; set; }
        public Nullable<int> organization_interest_rate { get; set; }
        public Nullable<System.DateTime> card_date { get; set; }
        public Nullable<int> account_type { get; set; }
        public Nullable<double> or_actual_commission_amount { get; set; }
        public Nullable<int> parent_agent_id { get; set; }
        public string parent_agent_name { get; set; }
        public string agent_pay_typeStr { get; set; }
    }
}
