//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manager_module_db
    {
        public string module_code { get; set; }
        public string module_name { get; set; }
        public string pater_code { get; set; }
        public Nullable<double> module_level { get; set; }
        public Nullable<double> is_menu { get; set; }
        public Nullable<double> is_action { get; set; }
        public string action_url { get; set; }
        public Nullable<decimal> order_by { get; set; }
        public Nullable<double> module_status { get; set; }
        public string creator_name { get; set; }
        public string creator_full_name { get; set; }
        public Nullable<System.DateTime> creator_time { get; set; }
        public string modifi_name { get; set; }
        public string modifi_full_name { get; set; }
        public Nullable<System.DateTime> modifi_time { get; set; }
        public Nullable<int> module_type { get; set; }
        public Nullable<int> crm_module_type { get; set; }
    }
}
