//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manager_role_db
    {
        public int id { get; set; }
        public string role_name { get; set; }
        public Nullable<double> role_status { get; set; }
        public string creator_name { get; set; }
        public string creator_full_name { get; set; }
        public Nullable<System.DateTime> creator_time { get; set; }
        public string modifi_name { get; set; }
        public string modifi_full_name { get; set; }
        public Nullable<System.DateTime> modifi_time { get; set; }
        public Nullable<int> top_agent_id { get; set; }
        public Nullable<int> role_type { get; set; }
        public int yunYingRole { get; set; }
        public Nullable<int> isRequote { get; set; }
        public int data_level { get; set; }
    }
}
