//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manager_function_db
    {
        public string function_code { get; set; }
        public string function_name { get; set; }
        public int function_type { get; set; }
        public int function_platform { get; set; }
        public string operator_name { get; set; }
        public System.DateTime operator_time { get; set; }
        public int order_by { get; set; }
        public int function_state { get; set; }
        public string function_parent_code { get; set; }
    }
}
