//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manager_module_button
    {
        public int id { get; set; }
        public string button_name { get; set; }
        public string pater_module { get; set; }
        public string action_url { get; set; }
        public string creator_name { get; set; }
        public System.DateTime creator_time { get; set; }
        public string modify_name { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public Nullable<int> delete_state { get; set; }
        public string button_code { get; set; }
    }
}
