//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tx_clues
    {
        public int id { get; set; }
        public int agentid { get; set; }
        public int smsid { get; set; }
        public string licenseno { get; set; }
        public int source { get; set; }
        public string sourcename { get; set; }
        public int casetype { get; set; }
        public int followupstate { get; set; }
        public string accidentremark { get; set; }
        public string smsrecivedtime { get; set; }
        public string dangerarea { get; set; }
        public string mobile { get; set; }
        public string ReportCaseNum { get; set; }
        public string ReportCasePeople { get; set; }
        public Nullable<int> HasInsureInfo { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int Deleted { get; set; }
        public string MoldName { get; set; }
        public string CarVIN { get; set; }
        public string city_name { get; set; }
        public int last_follow_id { get; set; }
        public string OrderNum { get; set; }
        public int CurrentAgentId { get; set; }
        public string AgentName { get; set; }
        public int ChosedModelId { get; set; }
        public sbyte ClueFromType { get; set; }
        public int ChosedCompanyId { get; set; }
        public string ChosedCompanyName { get; set; }
        public string CarOwner { get; set; }
        public sbyte IsMany { get; set; }
        public sbyte IsDrivering { get; set; }
        public sbyte Only4s { get; set; }
        public string ReceiveCarAddress { get; set; }
        public double ReceiveLng { get; set; }
        public double ReceiveLat { get; set; }
        public string ExpectedAddress { get; set; }
        public double ExpectedLng { get; set; }
        public double ExpectedLat { get; set; }
        public int Province { get; set; }
        public int City { get; set; }
        public int Area { get; set; }
        public string ProvinceName { get; set; }
        public string CityName { get; set; }
        public string AreaName { get; set; }
        public string FromAgentName { get; set; }
        public int ToAgentId { get; set; }
        public string ToAgentName { get; set; }
        public decimal FromRate { get; set; }
        public decimal ToRate { get; set; }
        public decimal MaintainAmount { get; set; }
        public System.DateTime AcceptedTime { get; set; }
        public string ChosedModelName { get; set; }
        public sbyte AcceptedState { get; set; }
        public sbyte ToSettledState { get; set; }
        public sbyte FromSettledState { get; set; }
        public System.DateTime ToSettledTime { get; set; }
        public System.DateTime FromSettledTime { get; set; }
        public decimal Profits { get; set; }
        public System.DateTime ExpectedFinishedTime { get; set; }
        public sbyte AgentType { get; set; }
    }
}
