//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tx_cluefollowuprecord
    {
        public int id { get; set; }
        public int clueid { get; set; }
        public int fromagentid { get; set; }
        public int toagentid { get; set; }
        public int state { get; set; }
        public int nextstate { get; set; }
        public int parentstate { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> nextfollowuptime { get; set; }
        public int ReciveCarType { get; set; }
        public string ReciveCarAea { get; set; }
        public int ReciveCaragentid { get; set; }
        public int ArrivalType { get; set; }
        public string SmsContent { get; set; }
        public int IsNotice { get; set; }
        public int Source { get; set; }
        public int roletype { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int Deleted { get; set; }
        public int loss_reason_id { get; set; }
        public Nullable<System.DateTime> expect_arrival_time { get; set; }
    }
}
