//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tx_mobile_agent_relationship
    {
        public int id { get; set; }
        public int agentid { get; set; }
        public string mobile { get; set; }
        public System.DateTime createTime { get; set; }
        public System.DateTime updatetime { get; set; }
        public int deleted { get; set; }
        public string mobile_imei { get; set; }
        public int mobile_type { get; set; }
    }
}
