//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tx_settlement_detail
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public string OrderNum { get; set; }
        public string LicenseNo { get; set; }
        public int ModelId { get; set; }
        public string ModleName { get; set; }
        public int FromAgentId { get; set; }
        public string FromAgentName { get; set; }
        public decimal FromRate { get; set; }
        public int ToAgentId { get; set; }
        public string ToAgentName { get; set; }
        public decimal MaintainAmount { get; set; }
        public decimal ToRate { get; set; }
        public sbyte AuditedState { get; set; }
        public string AuditedContent { get; set; }
        public System.DateTime AuditedTime { get; set; }
        public string AgentTel { get; set; }
        public int AgentId { get; set; }
        public string AgentName { get; set; }
        public int Operator { get; set; }
        public string OperatorName { get; set; }
        public sbyte ClueType { get; set; }
        public decimal FromExpend { get; set; }
        public decimal FromExpended { get; set; }
        public System.DateTime FromExpendedTime { get; set; }
        public sbyte FromPayType { get; set; }
        public decimal WithholdAmount { get; set; }
        public sbyte Invoiced { get; set; }
        public decimal ToEarning { get; set; }
        public decimal ToEarned { get; set; }
        public System.DateTime ToEarnedTime { get; set; }
        public sbyte ToPayType { get; set; }
        public decimal ChargeRate { get; set; }
        public decimal ExpectAmount { get; set; }
        public decimal ActualAmount { get; set; }
        public int ToSettlementId { get; set; }
        public int FromSettlementId { get; set; }
        public System.DateTime ToSettledTime { get; set; }
        public System.DateTime FromSettledTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
