//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int UserId { get; set; }
        public string NickName { get; set; }
        public string Name { get; set; }
        public string PwdMd5 { get; set; }
        public string IdentityCard { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
        public Nullable<int> Country { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> Province { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> PartArea { get; set; }
        public string ProvinceName { get; set; }
        public string CityName { get; set; }
        public string AreaName { get; set; }
        public string PartAreaName { get; set; }
        public string Address { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public string OperatorName { get; set; }
        public Nullable<System.DateTime> OperatorTime { get; set; }
        public Nullable<int> RegisterType { get; set; }
        public string Openid { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string weibo_token { get; set; }
        public string HeaderImg { get; set; }
        public Nullable<int> car_brand_id { get; set; }
        public string car_brand_name { get; set; }
        public Nullable<int> car_line_id { get; set; }
        public string car_line_name { get; set; }
        public Nullable<int> car_type_id { get; set; }
        public string car_type_name { get; set; }
    }
}
